export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="theme-adam"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"

source $ZSH/oh-my-zsh.sh

# Terminal history
HISTFILE=~/.zsh_history
HISTSIZE=999999999
SAVEHIST=$HISTSIZE

# Alias
alias virtual="source .env/bin/activate"
alias devmail="docker run -p 1080:1080 -p 1025:1025 maildev/maildev"
# alias python2="python"
# alias python="python3"

# NVM settings
# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
# export NVM_DIR=~/.nvm
# source $NVM_DIR/nvm.sh

# RVM settings
# export PATH="$PATH:$HOME/.rvm/bin"
# export NPM_CONFIG_REGISTRY="https://nexus.tooling.dvla.gov.uk/repository/npm-group/"

# Pyenv settings
# export PYENV_ROOT="$HOME/.pyenv"
# export PATH="$PYENV_ROOT/bin:$PATH"
# export PIPENV_PYTHON="$PYENV_ROOT/shims/python"
# eval "$(pyenv init -)"

# AWS setup stuff
# alias awslogin1="~/Documents/aws_login_script_part_1.sh"
# alias awslogin2="~/Documents/aws_login_script_part_2.sh"
# export AWS_ACCESS_KEY_ID=`jq -r '.Credentials.AccessKeyId' /tmp/coding_creds.txt`
# export AWS_SESSION_TOKEN=`jq -r '.Credentials.SessionToken' /tmp/coding_creds.txt`
# export AWS_SECRET_ACCESS_KEY=`jq -r '.Credentials.SecretAccessKey' /tmp/coding_creds.txt`

# Plugins
# plugin=(git pyenv)
plugin=(git)

# Setup for DupV5
export DOCKER_BUILDKIT=0
export COMPOSE_DOCKER_CLI_BUILD=0
export DOCKER_DEFAULT_PLATFORM=linux/amd64
export PATH="/usr/local/sbin:$PATH"
